### PR TITLE
Fixes version display and empty module compilation (fixes #264 #265)

### LINKED ISSUE #264: aqua-js: version is "unknown"
In the generated TS/JS file version isn't specified if compiling via `aqua-js`:
```
 * Aqua version: Unknown (JS)
```

Also, aqua-js --version doesn't work:
```
$ npx aqua-js --version
Aqua JS: node /sandbox/node_modules/@fluencelabs/aqua-cli/aqua-cli-experimental.js -m node_modules --version
Aqua JS: Missing expected flag --input!
Missing expected flag --output!
```

Version: `0.2.1-219`

### LINKED ISSUE #265: ERROR in a file with only imports and exports
The following Aqua code
```
import initTopicAndSubscribe, findSubscribers from "@fluencelabs/aqua-dht/pubsub.aqua"

export initTopicAndSubscribe, findSubscribers
```

Produces this error:
```
Aqua JS: node /sandbox/node_modules/@fluencelabs/aqua-cli/aqua-cli-experimental.js -m node_modules -i src/aqua -o src
Aqua JS: 2021.09.02 11:30:02 [ERROR] (offset is beyond the script, syntax errors) OneOfStr(136,List(alias, const, data, func, service))
```

However, if I add any definition, it works:
```
import initTopicAndSubscribe, findSubscribers from "@fluencelabs/aqua-dht/pubsub.aqua"

export initTopicAndSubscribe, findSubscribers

alias A: string
```

Version: `0.2.1-219`

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #265 
fixes #264

### CODE REVIEW

File: semantics/src/main/scala/aqua/semantics/Semantics.scala [hunk 1]
```diff
@@ -96,7 +91,9 @@ object Semantics extends Logging {
           NonEmptyChain
             .fromChain(state.errors)
             .fold[ValidatedNec[SemanticError[S], AquaContext]](Valid(ctx))(Invalid(_))
-        case (state, _) =>
+        case (_, _: EmptyModel) =>
```
Comment (alari) [inline semantics/src/main/scala/aqua/semantics/Semantics.scala:94]: Return the left operand

**Review by alari — APPROVED** [review]

**Comment by dzmitry-lahoda** [comment]
oh, just got this issue
