### PR TITLE
Model refactoring to isolate imports, exports

### LINKED ISSUE #97: Improve import behavior
Basically imports create a graph of dependencies between source files. Currently if you have a cycle in that graph the compiler will hang and crash with out of memory.

Quick fix: display an error message if a cyclic dependency has been found

Better fix: parse import statements, put them into a graph, do a topological sort on that graph, and include files in that order.

### LINKED ISSUE #114: Model (middle-end) refactoring
Each aqua file, once semantically analyzed, provides a model that later used to generate the target code.

Currently model loses a lot of data that will be needed later:
- Data types, service types, and all the other data that does not go to `air`
- Errors in semantic analysis
- Compilation logs

Model is not used when it must be (in linking).

Refactoring of the model will help with generating services from Aqua (#37) and linking (like #97, #62).

### LINKED ISSUE #125: Errors accumulate incorrectly
Errors accumulate and duplicate output in geometrical (or more) progression for some reason. It depends on the number of files.
Example:
`app.aqua`
```
import "chatApp.aqua"
import "service.aqua"

func createUser(nickname: string):
    on nickname:
        AppConfig.getApp()
        AppConfig.getApp()
```
`chatApp.aqua`
```
service AppConfig("affinidi/get-config"):
    getApp: -> string
    getLocalService: -> LocalService
```
`service.aqua`
```
service Service("affinidi/chat"):
    create_user(peer_id: string, relay_id: string, nickname: string) -> string
    chats_by_peer_id(peer_id: string) -> string
```
This example will print 10 error messages about that there is no `LocalService` type. If we import another random file to `app.aqua` there will be more than a hundred error messages. After some files, aqua compiler will be stopped with OOM.

### PR DESCRIPTION
**Pull request by alari**
Fixes #125
Fixes #114
Fixes #97
Referred to #30 
Referred to #31
Supersedes #135

### CODE REVIEW

File: semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala [hunk 1]
```diff
@@ -34,9 +34,11 @@ class ServiceSem[F[_]](val expr: ServiceExpr[F]) extends AnyVal {
                 arrows,
                 defaultId
               )
-              _ <- expr.id
+              _ <- (expr.id zip defaultId)
                 .fold(Free.pure[Alg, Unit](()))(idV =>
-                  (V.ensureIsString(idV) >> A.setServiceId(expr.name, idV)).map(_ => ())
+                  (V.ensureIsString(idV._1) >> A.setServiceId(expr.name, idV._1, idV._2)).map(_ =>
```
Comment (DieMyst) [inline semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala:39]: check if we need Value[F] as serviceId in a state

Comment (alari) [reply semantics/src/main/scala/aqua/semantics/expr/ServiceSem.scala:39]: Currently, it's not used. The intent is to enable language servers to highlight it when needed. So let's keep it for now.

**Review by DieMyst — APPROVED** [review]
