### PR TITLE
Add levenshtein distance to error messages, fix constant parsing

### LINKED ISSUE #201: "Undefined xx, available : ..." error suggests too many names
If there's an undefined identifier, the Aqua compiler kindly suggests possible names to try. However, it seems to do so without context-awareness. For example, it suggests function names in the position of function arguments, or it suggests a `nil` and `%last_error%` in the position of a function call.

```scala
import "dht.aqua"
import "@fluencelabs/aqua-lib/builtin.aqua"

func test():
    Op.noop()
    undefined_arrow()                         -- function call
    Op.identity(undefined_variable)   -- function argument
```

**Aqua Compiler 0.1.9-162** produces the following errors:
```log
[info] Aqua Compiler 0.1.9-162

/Users/folex/Development/fluencelabs/aqua-dht/npm/test.aqua:6:5
4 func test():
5     Op.noop()
6     undefined_arrow()
      ^^^^^^^^^^^^^^^==
      Undefined arrow, available: AquaDHT.renew_host_value, Srv.resolve_alias, Srv.remove, AquaDHT.set_expired_timeout, AquaDHT.register_key, Op.string_to_b58, Dist.make_module_config, Op.string_from_b58, Op.identity, Script.list, Srv.list, AquaDHT.propagate_host_value, Srv.add_alias, AquaDHT.set_stale_timeout, AquaDHT.merge, Dist.list_blueprints, Dist.get_interface, Op.noop, Peer.identify, AquaDHT.put_host_value, AquaDHT.set_host_expired_timeout, Peer.connect, Op.array_length, AquaDHT.evict_stale, Kademlia.neighborhood, AquaDHT.republish_key, Dist.add_blueprint, AquaDHT.put_value, AquaDHT.get_key_metadata, Script.remove, Peer.get_contact, Dist.make_blueprint, AquaDHT.merge_hack_get_values, Op.sha256_string, Script.add, AquaDHT.merge_two, Srv.get_interface, AquaDHT.clear_host_value, Kademlia.merge, Dist.add_module, AquaDHT.get_values, AquaDHT.republish_values, Srv.create, AquaDHT.clear_expired, Op.bytes_from_b58, Peer.is_connected, Op.array, Op.bytes_to_b58, Dist.list_modules, Op.concat, Peer.timestamp_ms, Peer.timestamp_sec, %last_error%, nil
7     Op.identity(undefined_variable)
8

/Users/folex/Development/fluencelabs/aqua-dht/npm/test.aqua:7:17
5     Op.noop()
6     undefined_arrow()
7     Op.identity(undefined_variable)
                  ^^^^^^^^^^^^^^^^^^=
                  Undefined name, available: AquaDHT.renew_host_value, Srv.resolve_alias, Srv.remove, AquaDHT.set_expired_timeout, AquaDHT.register_key, Op.string_to_b58, Dist.make_module_config, Op.string_from_b58, Op.identity, Script.list, Srv.list, AquaDHT.propagate_host_value, Srv.add_alias, AquaDHT.set_stale_timeout, AquaDHT.merge, Dist.list_blueprints, Dist.get_interface, Op.noop, Peer.identify, AquaDHT.put_host_value, AquaDHT.set_host_expired_timeout, Peer.connect, Op.array_length, AquaDHT.evict_stale, Kademlia.neighborhood, AquaDHT.republish_key, Dist.add_blueprint, AquaDHT.put_value, AquaDHT.get_key_metadata, Script.remove, Peer.get_contact, Dist.make_blueprint, AquaDHT.merge_hack_get_values, Op.sha256_string, Script.add, AquaDHT.merge_two, Srv.get_interface, AquaDHT.clear_host_value, Kademlia.merge, Dist.add_module, AquaDHT.get_values, AquaDHT.republish_values, Srv.create, AquaDHT.clear_expired, Op.bytes_from_b58, Peer.is_connected, Op.array, Op.bytes_to_b58, Dist.list_modules, Op.concat, Peer.timestamp_ms, Peer.timestamp_sec, %last_error%, nil
8
9

/Users/folex/Development/fluencelabs/aqua-dht/npm/test.aqua:7:17
5     Op.noop()
6     undefined_arrow()
7     Op.identity(undefined_variable)
                  ^^^^^^^^^^^^^^^^^^=
                  Undefined name, available: AquaDHT.renew_host_value, Srv.resolve_alias, Srv.remove, AquaDHT.set_expired_timeout, AquaDHT.register_key, Op.string_to_b58, Dist.make_module_config, Op.string_from_b58, Op.identity, Script.list, Srv.list, AquaDHT.propagate_host_value, Srv.add_alias, AquaDHT.set_stale_timeout, AquaDHT.merge, Dist.list_blueprints, Dist.get_interface, Op.noop, Peer.identify, AquaDHT.put_host_value, AquaDHT.set_host_expired_timeout, Peer.connect, Op.array_length, AquaDHT.evict_stale, Kademlia.neighborhood, AquaDHT.republish_key, Dist.add_blueprint, AquaDHT.put_value, AquaDHT.get_key_metadata, Script.remove, Peer.get_contact, Dist.make_blueprint, AquaDHT.merge_hack_get_values, Op.sha256_string, Script.add, AquaDHT.merge_two, Srv.get_interface, AquaDHT.clear_host_value, Kademlia.merge, Dist.add_module, AquaDHT.get_values, AquaDHT.republish_values, Srv.create, AquaDHT.clear_expired, Op.bytes_from_b58, Peer.is_connected, Op.array, Op.bytes_to_b58, Dist.list_modules, Op.concat, Peer.timestamp_ms, Peer.timestamp_sec, %last_error%, nil
8
9
```

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #201

### CODE REVIEW

File: semantics/src/main/scala/aqua/semantics/Levenshtein.scala [hunk 1]
```diff
@@ -0,0 +1,51 @@
+package aqua.semantics
+
+import scala.collection.mutable
+import scala.collection.mutable
```
Comment (alari) [inline semantics/src/main/scala/aqua/semantics/Levenshtein.scala:4]: Duplicate import

**Review by folex — APPROVED** [review]
