### PR TITLE
Capture and apply topology

### LINKED ISSUE #356: Closures do not capture topology
As of Aqua 0.6.0, there is no compiler infrastructure to capture topology. It can easily lead to bugs, like:

```python

func foo():
  -- Move execution to a known location
  on "some known peer":
    Srv "service that exists only there"
    closure = () -> ():
       Srv.call("this call should happen on some known peer")

  -- Shift execution – we don't have Srv resolved there
  on "another peer":
    -- Srv.call() --< will compile error, as Srv is not resolved here
    closure() --< will fail on runtime, trying to perform Srv.call on another peer

```

This problem can be solved with "Capture Topology" and "Apply Topology" primitives:

```python

func foo():
  -- Move execution to a known location
  on "some known peer":
    Srv "service that exists only there"
    #Capture(name=closure-topology-1)
    closure = () -> ():
       #OnCaptured(name=closure-topology-1):
         Srv.call("this call should happen on some known peer")

  -- Shift execution – we don't have Srv resolved there
  on "another peer":
    -- Srv.call() --< will compile error, as Srv is not resolved here
    closure()
    -- Here closure call will be desugared to:
    on "some known peer":
       Srv.call("this call should happen on some known peer")
    -- Which is absolutely correct

```

Changes needed:
- Introduce `CaptureTopologyTag`, `ApplyTopologyTag`
- During `inline` phase, names mangling should apply on topology tags
- `Topology` needs to remember the position of met `CaptureTopologyModel`s
- For `Topology.pathOn`, when got to an `ApplyTopologyModel`, should return the remembered captured `pathOn`

With this additions the bug will be fixed, and the compiler will have the required primitives to bind topology to function calls, which is useful for Abilities.

### PR DESCRIPTION
**Pull request by alari**
Fixes #356

### CODE REVIEW

File: model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala [hunk 1]
```diff
@@ -34,13 +34,49 @@ case class Topology private (
...
-    .later(cursor.tagsPath.collect { case o: OnModel =>
-      o
-    })
-    .memoize
+  val parent: Option[Topology] = cursor.moveUp.map(_.topology)
+
+  val parents: LazyList[Topology] =
+    LazyList.unfold(parent)(p => p.map(pp => pp -> pp.parent))
+
+  val capturedTopologies: Eval[Map[String, Topology]] =
```
Comment (DieMyst) [inline model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala:44]: docs

File: model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala [hunk 2]
```diff
@@ -34,13 +34,49 @@ case class Topology private (
...
+          case x =>
+            logger.trace(s"Skip $x")
+            cursor.toLastChild
+              .map(_.topology.capturedTopologies.map(_ ++ tops))
+              .getOrElse(Eval.now(tops))
+        }
+      )
+      .memoize
+
+  val pathOn: Eval[List[OnModel]] =
```
Comment (DieMyst) [inline model/transform/src/main/scala/aqua/model/transform/topology/Topology.scala:61]: docs

**Review by DieMyst — APPROVED** [review]
