### PR TITLE
Generate types from JSON

### LINKED ISSUE #435: Build types from JSON to compare it with aqua types
Right now there is no comparison of arguments from JSON and function arguments in `aqua run`. So, there will be no compilation error if JSON will be incorrect. Also, it will be useful in other parts of CLI, including future REPL implementation.

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #435 

If you will pass JSON with absent fields you will get an error.
For example:
```
aqua run -f 'identityArgsAndReturn(structField)'...
```
Where `structField` should be type of `StructType`:
```
data SubType:
  a: ?string
  b: []u32
  c: string
  d: string

data StructType:
  numField: u32
  arrField: []string
  arr2: []SubType
```
And we pass JSON where field `arr2` have objects with missed fields:
```
{
  "structField": {
    "numField": 42,
    "arrField": ["str1", "str2", "r43r34", "ferer"],
    "arr2": [{
      "a": "fef",
      "b": [1,2,3,4],
      "c": "erfer"
    },{
      "b": [1,2,3,4],
      "c": "erfer"
    }, {
        "a": "as",
        "d": "gerrt"
      }]
  }
}
```
We will get an error that points to these fields
```
Type for field 'structField.arr2.c' mismatch with argument. Expected: 'string' Given: '?string'

Type for field 'structField.arr2.d' mismatch with argument. Expected: 'string' Given: '?string'

```

### CODE REVIEW

File: cli/.js/src/main/scala/aqua/ArgOpts.scala [hunk 1]
```diff
@@ -42,15 +45,20 @@ object ArgOpts {
...
               case LiteralToken(value, ts) =>
-                LiteralRaw(value, ts)
+                validNel(LiteralRaw(value, ts))
               case VarToken(name, _) =>
-                // TODO why BottomType?
-                VarRaw(name.value, BottomType)
-            }
-
-            validNel(CliFunc(expr.funcName.value, args, expr.ability.map(_.name)))
+                // TODO it will be changed after 'jsTypeToAqua'
```
Comment (alari) [inline cli/.js/src/main/scala/aqua/ArgOpts.scala:52]: I don't understand what this comment means. You need something to do later? What and why? Or `jsTypeToAqua` is a name of a function that's to be called?

File: cli/.js/src/main/scala/aqua/json/JsonEncoder.scala [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+  def compareAndGetWidestType(
+    name: String,
+    ltV: ValidatedNec[String, Type],
+    rtV: ValidatedNec[String, Type]
+  ): ValidatedNec[String, Type] = {
+    (ltV, rtV) match {
+      case (Validated.Valid(lt), Validated.Valid(rt)) =>
+        (lt, rt) match {
+          case (lt, rt) if lt == rt => validNec(lt)
+          case (_ @BottomType, ra @ ArrayType(_)) => validNec(ra)
```
Comment (alari) [inline cli/.js/src/main/scala/aqua/json/JsonEncoder.scala:42]: just `BottomType`, no need for `_ @`

File: cli/.js/src/main/scala/aqua/json/JsonEncoder.scala [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+              .view
+              .mapValues(_.map(_._2))
+              .map {
+                case (name, t :: Nil) =>
+                  compareAndGetWidestType(name, validNec(t), validNec(BottomType)).map(t =>
+                    (name, t)
+                  )
+                case (name, lt :: rt :: Nil) =>
+                  compareAndGetWidestType(name, validNec(lt), validNec(rt)).map(t => (name, t))
+                case _ => invalidNec("Unexpected. The list can only have 1 or 2 arguments.")
```
Comment (alari) [inline cli/.js/src/main/scala/aqua/json/JsonEncoder.scala:62]: I am absolutely sure that this error message will deeply confuse the user, if ever occur. Which list? This list appears only as a part of merging process, it does not exist for the user.

**Review by alari — APPROVED** [review]
