### PR TITLE
69 wrong varnames

### LINKED ISSUE #69: Incorrect variable naming when a variable with the same name is used in two interconnected functions
Aqua code:

```
service Demo("demo"):
	get42: -> u64

func one() -> u64:
    variable <- Demo.get42()
    <- variable

func two() -> u64:
    variable <- one()
    <- variable

```

**actual** generated air for the function `two` 

```
(xor
 (seq
  (seq
   (call %init_peer_id% ("getDataSrv" "relay") [] relay)
   (call %init_peer_id% ("demo" "get42") [] variable0)
  )
  (call %init_peer_id% ("callbackSrv" "response") [variable])
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error%])
)

```

**expected**

```
(xor
 (seq
  (seq
   (call %init_peer_id% ("getDataSrv" "relay") [] relay)
   (call %init_peer_id% ("demo" "get42") [] variable0)
  )
  (call %init_peer_id% ("callbackSrv" "response") [variable0])
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error%])
)

```

variable0 instead of variable or the vice versa.

### PR DESCRIPTION
**Pull request by alari**
Fixes #69

### CODE REVIEW

File: model/src/main/scala/aqua/model/ScriptModel.scala [hunk 1]
```diff
@@ -1,21 +1,46 @@
...
+object ScriptModel {
+
+  implicit object SMMonoid extends Monoid[ScriptModel] {
+    override def empty: ScriptModel = ScriptModel()
+
+    override def combine(x: ScriptModel, y: ScriptModel): ScriptModel =
+      ScriptModel(x.funcs ++ y.funcs, x.services ++ y.services, x.types ++ y.types)
+  }
+
+  def toScriptPart(m: Model): Option[ScriptModel] = m match {
```
Comment (DieMyst) [inline model/src/main/scala/aqua/model/ScriptModel.scala:40]: what does this function do? maybe add a doc?

File: model/src/main/scala/aqua/model/func/ArgsCall.scala [hunk 2]
```diff
@@ -0,0 +1,47 @@
+package aqua.model.func
+
+import aqua.model.{ValueModel, VarModel}
+import aqua.types.{ArrowType, DataType}
+import cats.syntax.functor._
+
+case class ArgsCall(args: List[ArgDef], call: List[Call.Arg]) {
```
Comment (DieMyst) [inline model/src/main/scala/aqua/model/func/ArgsCall.scala:7]: what it represents? why `args` is plural and `call` is singular? frustrating, given that the next is the `zipped` method
