### PR TITLE
53 219 issues

### LINKED ISSUE #53: Cannot make a function that returns a literal
Aqua:
```func helloWorldStr() -> string:
    <- "Hello, World!"
```
Error:
```
Unknown model: EmptyModel(compiler state monoid empty |+| Root contains not a script model, it's EmptyModel(Function body is not a funcOp, it's EmptyModel(Return makes no model)))
```

### LINKED ISSUE #219: Disable Top, Bottom types parsing
Aqua has internal Top and Bottom types. They can be used explicitly in service definitions, which does not seem secure.

Let's remove Top, Bottom types from the parser.

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #53 return literal only in functions
fixes #219 disable top-bottom parsing

### CODE REVIEW

File: model/src/main/scala/aqua/model/func/raw/FuncOps.scala [hunk 1]
```diff
@@ -78,4 +79,8 @@ object FuncOps {
 
   def next(item: String): FuncOp =
     FuncOp.leaf(NextTag(item))
+
+  lazy val empty: FuncOp =
+    FuncOp(Cofree[Chain, RawTag](EmptyTag, Eval.now(Chain.empty)))
```
Comment (alari) [inline model/src/main/scala/aqua/model/func/raw/FuncOps.scala:84]: Use `FuncOp.leaf(EmptyTag)`

**Review by alari — APPROVED** [review]
