### PR TITLE
Check service definition fields in TS and JS, fix functions and services count in output

### LINKED ISSUE #304: TypeScript backend: register{ServiceName} accepts any object
I've faced a hard-to-debug typo in https://github.com/galtproject/geesome-libs/pull/56

In short, there was two services `A` & `B`. The code was trying to use `registerA` while passing it `new BDef`.

I think `register{ServiceName}` functions must check that the passed object has all the fields it must have to conform to `{ServiceName}Def` interface, and throw an error if it doesn't

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #304

### CODE REVIEW

File: backend/js/src/main/scala/aqua/backend/js/JavaScriptService.scala [hunk 1]
```diff
@@ -64,16 +66,21 @@ case class JavaScriptService(srv: ServiceRes) {
...
-      |          if (req.serviceId !== serviceId) {
-      |              next();
-      |              return;
-      |          }
-      |  
-      |          ${fnHandlers}
-      |  
-      |          next();
-      |      });
+      |    let incorrectServiceDefinitions = missingFields(service, [${membersNames.map { n => s"'$n'"}.mkString(", ")}]);
```
Comment (coder11) [inline backend/js/src/main/scala/aqua/backend/js/JavaScriptService.scala:69]: It's better to use `const` for every declaration which is not going to be reassigned

File: backend/ts/src/main/scala/aqua/backend/ts/TypeScriptService.scala [hunk 2]
```diff
@@ -111,6 +113,11 @@ case class TypeScriptService(srv: ServiceRes) {
       |        service = args[2];
       |    }
       |
+      |    let incorrectServiceDefinitions = missingFields(service, [${membersNames.map { n => s"'$n'" }.mkString(", ")}]);
```
Comment (coder11) [inline backend/ts/src/main/scala/aqua/backend/ts/TypeScriptService.scala:116]: It's better to use `const` for every declaration which is not going to be reassigned

**Review by coder11 — APPROVED** [review]
