### PR TITLE
Don't print help on errors in CLI

### LINKED ISSUE #493: Do not print entire help on error in CLI arguments
Right now, if you do a mistake, like:
```
aqua gemote list_modules
```

You receive A VERY BIG pile of text: error and the whole --help. But you really care only about error:
```
% aqua gemote list_modules
Unexpected argument: gemote

...
```

So I suggest to instead print the following:
```
% aqua gemote list_modules
Unexpected argument: gemote

Try 'aqua --help' for usage instructions
```

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #493

### CODE REVIEW

File: cli/.js/src/main/scala/aqua/CommandBuilder.scala [hunk 1]
```diff
@@ -1,6 +1,7 @@
 package aqua
 
 import aqua.builder.{ArgumentGetter, Service}
+import aqua.io.OutputPrinter
```
Comment (alari) [inline cli/.js/src/main/scala/aqua/CommandBuilder.scala:4]: Is it used?

File: cli/src/main/scala/aqua/AquaCli.scala [hunk 2]
```diff
@@ -130,33 +138,48 @@ object AquaCli extends IOApp with Logging {
...
           }
         }
     }
   }
 
+  def handleCommand(args: List[String]): IO[ExitCode] = {
+    val command = Command("aqua", "Aqua Compiler", false)(main[IO](runtime))
+    for {
+      parseResult: Either[Help, IO[ExitCode]] <- Sync[IO].delay(
+        command.parse(PlatformApp.ambientArgs getOrElse args, sys.env)
```
Comment (alari) [inline cli/src/main/scala/aqua/AquaCli.scala:161]: Could you please add a comment what happens there. WTF ambientArgs?

**Review by alari — APPROVED** [review]
