### PR TITLE
#366 Add secret key option #373 Handle timeout errors

### LINKED ISSUE #366: Add `private_key` into `run` options to make it possible to customize init_peer_id

### LINKED ISSUE #373: Handle timeout exceptions in `run` command
It's unclear stack trace right now:
```
scala.scalajs.js.JavaScriptException: Request timed out after 7000 for --someFuncToRun--
    at $c_sjs_js_Thenable$ThenableOps$.scala$scalajs$js$Thenable$ThenableOps$$$anonfun$toFuture$2__O__s_concurrent_Promise__sjs_js_$bar (file:///home/joera/.nvm/versions/node/v14.15.2/lib/node_modules/@fluencelabs/aqua/aqua.js:29743:17)
    at file:///home/joera/.nvm/versions/node/v14.15.2/lib/node_modules/@fluencelabs/aqua/aqua.js:29732:295 {
  jl_Throwable__f_s: null,
  jl_Throwable__f_e: null,
  jl_Throwable__f_enableSuppression: true,
  jl_Throwable__f_writableStackTrace: true,
  jl_Throwable__f_stackTraceStateInternal: 'Request timed out after 7000 for --someFuncToRun--',
  jl_Throwable__f_stackTrace: null,
  jl_Throwable__f_suppressed: null,
  sjs_js_JavaScriptException__f_exception: 'Request timed out after 7000 for --someFuncToRun--'
  ```
  
  Will be better to write user-friendly message

### PR DESCRIPTION
**Pull request by DieMyst**
fixes #366 
fixes #373

### CODE REVIEW

File: cli/.js/src/main/scala/aqua/run/RunOpts.scala [hunk 1]
```diff
@@ -33,6 +34,16 @@ object RunOpts extends Logging {
         "/dns4/kras-00.fluence.dev/tcp/19001/wss/p2p/12D3KooWR4cv1a8tv7pps4HH6wePNaK6gf1Hww5wcCMzeWxyNw51"
       )
 
+  val secretKeyOpt: Opts[Array[Byte]] =
+    Opts
+      .option[String]("sk", "Secret key in base64. Requests will be initialized with this key.", "s")
```
Comment (folex) [inline cli/.js/src/main/scala/aqua/run/RunOpts.scala:39]: I think "initialized with this key" is highly confusing. I think `--help` isn't a place to educate people on secret keys and peer ids, so let's just describe data format and leave it at it.

```suggestion
      .option[String]("sk", "Ed25519 32-byte secret key in base64", "s")
```

File: cli/.js/src/main/scala/aqua/run/RunOpts.scala [hunk 2]
```diff
@@ -33,6 +34,16 @@ object RunOpts extends Logging {
...
+      .mapValidated { s =>
+        val decoder = Base64.getDecoder
+        Validated.catchNonFatal {
+          decoder.decode(s)
+        }.leftMap(t => NonEmptyList.one("Secret key must be valid base64 string: " + t.getMessage))
```
Comment (folex) [inline cli/.js/src/main/scala/aqua/run/RunOpts.scala:44]:
```suggestion
        }.leftMap(t => NonEmptyList.one("base64 decoding failed: " + t.getMessage))
```

**Review by folex — APPROVED** [review]
