### PR TITLE
Fixes #86

### LINKED ISSUE #86: Incorrect air for if statement without else branch
Example aqua:

```
import "builtin.aqua"

func ifWithNoElse(condition: u32):
    if condition == 1:
        Peer.identify()
```

Generates **actual** output:

```
(xor
 (seq
  (seq
   (call %init_peer_id% ("getDataSrv" "relay") [] relay)
   (call %init_peer_id% ("getDataSrv" "condition") [] condition)
  )
  (match condition 1
   (call %init_peer_id% ("peer" "identify") [])
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error%])
)

```

**Expected** output (match wrapped with the xor statement):

```
(xor
 (seq
  (seq
   (call %init_peer_id% ("getDataSrv" "relay") [] relay)
   (call %init_peer_id% ("getDataSrv" "condition") [] condition)
  )
  (xor
   (match condition 1
    (call %init_peer_id% ("peer" "identify") [])
   )
   (null)
  )
 )
 (call %init_peer_id% ("errorHandlingSrv" "error") [%last_error%])
)

```

### PR DESCRIPTION
**Pull request by alari**
Wraps a single MatchMismatch with xor and null on the right.

### CODE REVIEW

File: backend/air/src/main/scala/aqua/backend/air/AirGen.scala [hunk 1]
```diff
@@ -40,41 +40,33 @@ object AirGen {
     case list => list.reduceLeft(SeqGen)
   }
 
+  def fixMatchMismatch(ag: AirGen): AirGen = ag match {
```
Comment (DieMyst) [inline backend/air/src/main/scala/aqua/backend/air/AirGen.scala:43]: what does it fix? maybe add a comment or a link to an issue. Or rename it

**Review by DieMyst — CHANGES_REQUESTED** [review]
