### PR TITLE
Fix type convertion for option type

### LINKED ISSUE #288: Argument types in interfaces don't match values that pass in fact
This aqua code
```
service OptionString("opt_str"):
  checkOption(str: ?string) -> string

func emptyString() -> ?string:
  valueEmpty: ?string
  <- valueEmpty

func checkEmpty() -> string:
  empty <- emptyString()
  res <- OptionString.checkOption(empty)
  <- res
```
generates this interface for service:
```
 export interface OptionStringDef {
     checkOption: (str: string | null, callParams: CallParams<'str'>) => string;
 }
 ```
but an array passes in implementation. `[]` or `["some_str"]` will be printed in this example. Instead of `null` or `"some_str"`
```
registerOptionString({
        checkOption: (str: string | null) => {
            console.log(str)
        }
    })
```

### PR DESCRIPTION
**Pull request by coder11**
fixes #288

### CODE REVIEW

File: backend/js/src/main/scala/aqua/backend/js/JavaScriptCommon.scala [hunk 1]
```diff
@@ -18,8 +18,15 @@ object JavaScriptCommon {
...
     val arrowArgumentsToCallbackArgumentsList =
       at.domain.toList.zipWithIndex
-        .map(_._2)
-        .map(idx => s"req.args[$idx]")
+        .map((`type`, idx) => {
+          val valueFromArg = s"req.args[$idx]"
+          `type` match {
+            case OptionType(t) =>
+              s"${valueFromArg}.length === 0 ? null : ${valueFromArg}[0]" +
+                s""
```
Comment (DieMyst) [inline backend/js/src/main/scala/aqua/backend/js/JavaScriptCommon.scala:26]: delete empty string `s""` i guess
